language: cpp
dist: trusty
env: COMPILER=g++-7
compiler: gcc
git:
  depth: 1
addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:mhier/libboost-latest'
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      # Version number may need to be incremented if the boost ppa is updated.
      # If there are issues installing boost, check ppa:mhier/libboost-latest
      # for what the version number here should be.
      - boost1.68
install:
  ## Install CMake 3.13.2
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR}
  - cd ${DEPS_DIR}
  - travis_retry wget https://github.com/Kitware/CMake/releases/download/v3.13.2/cmake-3.13.2-Linux-x86_64.tar.gz
  - echo "6370de82999baafc2dbbf0eda23007d93f78d0c3afda8434a646518915ca0846  cmake-3.13.2-Linux-x86_64.tar.gz" > cmake_sha256.txt
  - sha256sum -c cmake_sha256.txt
  - tar -xzf cmake-3.13.2-Linux-x86_64.tar.gz
  - mv cmake-3.13.2-Linux-x86_64 cmake-install
  - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  - cd ${TRAVIS_BUILD_DIR}
script:
  - MAKE_DIR="${TRAVIS_BUILD_DIR}/build"
  - mkdir ${MAKE_DIR}
  - cd ${MAKE_DIR}
  - cmake ${TRAVIS_BUILD_DIR}
  - make  # build
  - make check  # run tests
